kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            ns: default
      ports:                                                                                                                                                                                                                                  
      - protocol: TCP
        port: 8080
    - from:
      - namespaceSelector:
          matchLabels:
            ns: kube-system
      ports:                                                                                                                                                                                                                                  
      - protocol: TCP
        port: 8080

