apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-authorized-keys"
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "ssh.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  authorized_keys: {{ .Values.ssh.public_key | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-egg"
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "ssh.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  EGG: {{ .Values.egg.env | quote }}
