apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6667
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh.selectorLabels" . | nindent 4 }}
