kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "egg.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "egg.name" . }}
    chart: {{ template "egg.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "egg.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: ssh
      ports:
      - protocol: TCP
        port: 8080
