apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "honk.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "honk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "honk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "honk.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ .Chart.Name }}-token"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
