{{- $fullName := include "entry.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "entry.labels" . | nindent 4 }}
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
            
