apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secret-egg"
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "entry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  EGG: {{ .Values.egg.secret | b64enc | quote }}
  
