apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "entry.serviceAccountName" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "entry.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "entry.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "entry.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: {{ include "entry.serviceAccountName" . }}
