name: Build images and push to dockerhub
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build-all-and-Push-to-DH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build entry
        id: entry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: docker-images/entry/
          build_args: GHA_EASTER_EGG=${{ secrets.GHA_EASTER_EGG }}
          repository: nodyd/e20-entry
          tags: latest

      - name: Build ssh
        id: ssh
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: docker-images/ssh/
          repository: nodyd/e20-ssh
          tags: latest

      - name: Build egg
        id: token
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: docker-images/egg/
          repository: nodyd/e20-egg
          tags: latest
